### ISSUE TITLE
Adding schema for individual components 

### ISSUE THREAD

**Issue by marshallmcdonnell** [stuchalk/scidata#5]
This is an umbrella ticket for adding the initial draft of schema to SciData.

The plan is to create small, modular schemas to facilitate structuring the larger overall SciData schema (see [Structuring complex schema](https://json-schema.org/understanding-json-schema/structuring.html#structuring) ) 

Schemas:
- [x] Basis Set
- [x] Calculation
- [x] Chemical
- [ ] ~Compound~
- [x] Computer
- [ ] ~Condition~
- [x] Dataset (PR #9)
- [x] General (skip?, see Issue #12)
- [ ] ~Material~
- [x] Measurement (PR #11)
- [x] Methodology
- [x] Molecular System
- [ ] ~Organism~
- [x] Parameter (PR #8)
- [x] Procedure
- [x] Resource (PR #10)
- [ ] ~Sample~
- [x] Software
- [x] Substance
- [x] System
- [ ] ~Target~
- [x] Unit (PR #6)
- [x] Value (PR #7)
- [x] SciData (Overall)

**Comment by stuchalk** [comment]
Marshall, this is awesome and something that will really help users to implement SciData.  Just so you know because of my NSF grant I will be revising SciData when I find data elements that need to be represented but cannot logically fit into the current framework (i.e. safety info, results, etc.). So, the spec will change over time...

Two other thoughts:
- We should think about is how to link the semantic representation of the data element in ScIData into a JSON Form.  It would be amazing if when a JSON Form is defined it not only represents the datatype but also the semantic meaning.  If this were possible it might be that you could link (automatically) a controlled vocabulary or database of ontologically defined entities.  The result would be a form populating a field with a dropdown menu or a live search box that only allows specific values to be entered.
- In the context a form is used it would be great if before the form is rendered it automatically pulls local settings for some of the fields so they do not have to be shown (e.g. current userid etc.).  Maybe this is not part of a JSON form but a local add-on that defines elements to be pulled in in the background.

I am happy to work with you to iterate the forms - if we can get them to fit your need then that is a paper we can write to get others to do the same :)

**Comment by marshallmcdonnell** [comment]
> So, the spec will change over time...

Understood and no problem, this will get some initial schema down and can modify them with changes to SciData.

>  It would be amazing if when a JSON Form is defined it not only represents the datatype but also the semantic meaning.  If this were possible it might be that you could link (automatically) a controlled vocabulary or database of ontologically defined entities. The result would be a form populating a field with a dropdown menu or a live search box that only allows specific values to be entered.

Completely agree! Not exactly sure all the details but have that same goal in mind. As the schema and JSONForms get more complete to the full SciData scope (as is now), we should probably have a discussion on how to move stuff forward that way.

> In the context a form is used it would be great if before the form is rendered it automatically pulls local settings for some of the fields so they do not have to be shown (e.g. current userid etc.). Maybe this is not part of a JSON form but a local add-on that defines elements to be pulled in in the background.

Yes, agree, if there is say a login to populate userid and then author information, that can all get dropped from the JSONForm UI and already be in the JSON-LD in the background or if you have some Guest login, they can fill that in instead. Just a thought up example. I have some of the defaults in the main SciData schema I plan to do that way (ie "author type" is one that probably won't change or limit it to a drop-down of choices https://github.com/stuchalk/scidata/blob/9e0149eb02fda2caae324301713319b4e270ea47/examples/ph.jsonld#L21)

> I am happy to work with you to iterate the forms - if we can get them to fit your need then that is a paper we can write to get others to do the same :)

Sounds great! :+1: and definitely more than happy if you postdoc wants to contribute and be an author if so.

Thanks for feedback! I'll try to keep track of PRs for all these here as they come in.

**Comment by SmithRWORNL** [comment]
@marshallmcdonnell I need permission to push a branch on this repo for this issue.

**Comment by marshallmcdonnell** [comment]
@stuchalk is it okay to include @SmithRWORNL as a contributor to this repo so we can work on the schema directly (instead of from a fork)?

**Comment by stuchalk** [comment]
I already invited them... :)

**Comment by marshallmcdonnell** [comment]
Awesome, thanks! @SmithRWORNL let us know if you are still blocked.

**Comment by SmithRWORNL** [comment]
Addressed by https://github.com/stuchalk/scidata/pull/25

**Comment by marshallmcdonnell** [comment]
@stuchalk just an update, @SmithRWORNL has all the schema in for this ticket so closing it out.

I did mark through the schema that were not created in this original ticket because those entities no longer exist in the SciData JSONLD framework.

I'll open a separate ticket to do the packaging of the schema as a library (i.e. for python)

We would use this to validate SciData JSONLD for web services
